### ISSUE TITLE
Multiple language support ?

### ISSUE THREAD

**Issue by chrisribe** [jbrooksuk/node-summary#26]
Is there a plan to support multiple languages in the future? How would one implement this?

**Comment by chrisribe** [comment]
Ah sorry just read the blog post this should work in other languages.... 
http://thetokenizer.com/2013/04/28/build-your-own-summary-tool/

Well will need to test an see.
Thanks

**Comment by jbrooksuk** [comment]
Give it a go and let me know :)

**Comment by masasron** [comment]
Works great on Hebrew 👍

**Comment by jbrooksuk** [comment]
👍
