### ISSUE TITLE
Publish latest to npm?

### ISSUE THREAD

**Issue by michaelBenin** [jbrooksuk/node-summary#29]
Hi,

It would be great if we could do a minor version bump and publish the latest build of this to NPM with that bug fix we just merged. 

Thanks!

**Comment by djm158** [comment]
Any update on this? Is this project still being maintained or are there any active forks?

**Comment by fungilation** [comment]
I just keep my own fork with local file:// package on yarn

**Comment by jbrooksuk** [comment]
I'll do this now, if I can 👍

**Comment by jbrooksuk** [comment]
https://github.com/jbrooksuk/node-summary/releases/tag/1.2.0
