### ISSUE TITLE
Seeing import _ from 'lodash' error

### ISSUE THREAD

**Issue by sidster-io** [jbrooksuk/node-summary#46]
node_modules/node-summary/lib/summary.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'lodash'

on node version v11.6.0

**Comment by jbrooksuk** [comment]
Can you try the version on master?

**Comment by sidster-io** [comment]
Sorry for the late reply. Will try it out 👍🏽

**Comment by sidster-io** [comment]
Running into a new issue.
Added "node-summary": "git+https://github.com/jbrooksuk/node-summary.git#master" to package.json
Seeing error ```/node_modules/node-summary/lib/summary.js:1
(function (exports, require, module, __filename, __dirname) { import { convertHTMLToText, getTitle } from './helpers/html'```

**Comment by Niek** [comment]
Same error as @sidster-io from the master branch. @jbrooksuk maybe you need to add ``"type": "module"`` to the package.json?

**Comment by Catsvilles** [comment]
Same error here, v14.1.0

**Comment by jbrooksuk** [comment]
> Same error as @sidster-io from the master branch. @jbrooksuk maybe you need to add `"type": "module"` to the package.json?

Possibly! I'm not overly familiar with how this works to be honest. Are you able to test this?

**Comment by shadowtime2000** [comment]
I think the problem is that you are using ES syntax along with CommonJS. You could try going through the code and make it work with CommonJS syntax. What I mean is changing statements like `import {convertHTMLToText, getTitle} from './helpers/html.js';` to
`const {convertHTMLToText, getTitle} = require("./helpers/html.js");`. You would also have to change export statements from `export const getTitle = htmlBody = {<function code here>}` to `module.exports.getTitle = (htmlBody) => {<function code here>}`

**Comment by TroniPM** [comment]
I created a pull request fixing this issue(https://github.com/jbrooksuk/node-summary/pull/50). You can use that instead the main package by using the command (or just wait him fix the issue / or merge the PR):
 `npm install https://github.com/TroniPM/node-summary`

**Comment by suresharam** [comment]
@jbrooksuk Looks like the master version is not in npm and the issue continues. Can you please publish master version to npm ?

<img width="1160" alt="Screenshot 2021-02-03 at 4 24 04 PM" src="https://user-images.githubusercontent.com/10445578/106737057-3ea4f100-663c-11eb-806c-2692e58504bd.png">

**Comment by UnnikrishnanBhargavakurup** [comment]
```
/node_modules/node-summary/lib/summary.js:1
import _ from 'lodash'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by jingkang99** [comment]
on windows with node v16.14.0

import _ from 'lodash'
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by Valentine-Mario** [comment]
> I created a pull request fixing this issue(#50). You can use that instead the main package by using the command (or just wait him fix the issue / or merge the PR): `npm install https://github.com/TroniPM/node-summary`

This works fine. Thank you

**Comment by decidev22** [comment]
> npm install https://github.com/TroniPM/node-summary

This still works like a charm! Thank you!
